[[main]]
  name = "about"
  url = "#about"
  weight = 1

[[main]]
  name = "posts"
  url = "/posts/"
  weight = 2

[[main]]
  name = "isa"
  url = "/docs/"
  weight = 3
  
[[main]]
  name = "book review"
  url = "/breview/"
  weight = 4